### ISSUE TITLE
some questions about config.py

### ISSUE THREAD

**Issue by zhang0391** [n0obcoder/NIH-Chest-X-Rays-Multi-Label-Image-Classification-In-Pytorch#2]
Hello, what's the meaning of the frist five lines of the config.py and how should I modify them?pkl_dir_path             = 'pickles'
train_val_df_pkl_path    = 'train_val_df.pickle'
test_df_pkl_path         = 'test_df.pickle'
disease_classes_pkl_path = 'disease_classes.pickle'
models_dir               = 'models'

**Comment by n0obcoder** [comment]
Hi @zhang0391  ! Thanks for reaching out. The first 5 lines are quite simple. 
* `pkl_dir_path`  is the name of the  directory that is created in your working directory where all the 
   pickle files are saved. You dont have to manually make this directory. It gets created 
   automatically.
* `train_val_df_pkl_path` is the name of the pickle file which holds all the information about the train 
   n val files. Actually what happens is that, when you run the code, the train, val and test file paths 
   are  extracted from a csv. This takes some time. So the code reads the file names and the 
   respectve diseases only for the forst time when it is run. It then saves those info in pickles. So 
   that you wouldn't have to wait for all this the next time you run the code.
* `test_df_pkl_path` same as above
* `disease_classes_pkl_path` is the path of the pickle which contains the exhaustive list of all the 
   diseases (in alphabetical order)
* `models_dir` is the name of the directory where all your models are saved. You dont have to  
   manually make this directory. It gets created automatically.

Please let me know if this solves your problem :)

**Comment by zhang0391** [comment]
So train_val_df_pkl_path is the file named train_val_list.txt in NIH Chest X-rays, is that right?

**Comment by n0obcoder** [comment]
no.  

although `train_val_list.txt` is present in the `NIH Chest X-rays`, but `train_val_df_pkl_path` is different from `train_val_list.txt`.

`NIH Chest X-rays` has a `train_val_list.txt` which has all the image names and the diseases that are present in those images.

You need to read that txt file and make a dataframe, which would requires you to do some preprocessing on the disease names. It takes some time. So  i decided to do the preprocessing only for the first time that the code runs by saving all that processed info into a pickle. 

So `train_val_df_pkl_path` is the path where a pickle file will be saved containing all that processed info so that you dont have to wait everytime when you run the code.

please let me know if it makes sense to you. :)

**Comment by zhang0391** [comment]
So the five lines are only the names of the path and I don't need to do any modification on them, right?

**Comment by n0obcoder** [comment]
you are right. you dont need to change them.
it is all set up for you to run the code. you maybe wanna experiment with the model architecture though and maybe share your results if you get some promising results. : D

**Comment by zhang0391** [comment]
Hello, I meet another problem when I run the file main.py, the result is as follows:
-----Initial Dataset Information-----
num images in train_dataset   : 0
  File "C:\softwares\anaconda3\envs\zzrr\lib\site-packages\torch\utils\data\dataloader.py", line 176, in __init__
num images in val_dataset     : 0
    sampler = RandomSampler(dataset)
num images in XRayTest_dataset: 0
  File "C:\softwares\anaconda3\envs\zzrr\lib\site-packages\torch\utils\data\sampler.py", line 66, in __init__
-------------------------------------
"value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

Process finished with exit code 1
I wonder why it is like this.

**Comment by n0obcoder** [comment]
hi @zhang0391 .
Let's first confirm if you are able to read the images properly or not. When you run the code, it must print the shape of train_val_df (in the `get train_val_df ` section {line 29} of datasets.py)

can you pls share what gets printed there ?

**Comment by zhang0391** [comment]
The whole result is as follows:
C:\softwares\anaconda3\envs\zzrr\python.exe E:/Git/NIH-Chest-X-Rays-Multi-Label-Image-Classification-In-Pytorch-master/main.py

device: cuda

Overwriting stage to 1, as the model training is being done from scratch
TRAINING THE MODEL FROM SCRATCH

data\NIH Chest X-rays\Data_Entry_2017.csv found: True
self.df.shape: (12, 2)

  0%|          | 0/1 [00:00<?, ?it/s]train_val_df.pickle: loaded
self.train_val_df.shape: (1, 2)

Sampling the huuuge training dataset
100%|██████████| 1/1 [00:00<00:00, 100.42it/s]

disease_classes.pickle: already exists

self.all_classes_dict: {'No Finding': 1}

self.df.shape: (12, 2)

Traceback (most recent call last):
test_df.pickle: loaded
self.test_df.shape: (0, 0)
  File "E:/Git/NIH-Chest-X-Rays-Multi-Label-Image-Classification-In-Pytorch-master/main.py", line 83, in <module>

    train_loader = torch.utils.data.DataLoader(train_dataset, batch_size = batch_size, shuffle = True)
-----Initial Dataset Information-----
num images in train_dataset   : 0
  File "C:\softwares\anaconda3\envs\zzrr\lib\site-packages\torch\utils\data\dataloader.py", line 176, in __init__
num images in val_dataset     : 0
    sampler = RandomSampler(dataset)
num images in XRayTest_dataset: 0
  File "C:\softwares\anaconda3\envs\zzrr\lib\site-packages\torch\utils\data\sampler.py", line 66, in __init__
-------------------------------------
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

Process finished with exit code 1

**Comment by n0obcoder** [comment]
there seems to a some problem with your `self.df.shape`.

can you check the shape of the dataframe after reading the `Data_Entry_2017.csv` ?

**Comment by n0obcoder** [comment]
@zhang0391 , it should look like this-

```
device: cuda

Overwriting stage to 1, as the model training is being done from scratch
TRAINING THE MODEL FROM SCRATCH

data/NIH Chest X-rays/Data_Entry_2017.csv found: True
self.df.shape: (112120, 2)

train_val_df.pickle: loaded
self.train_val_df.shape: (86524, 2)
```

**Comment by zhang0391** [comment]
Yeah, but why the result of mine is different from yours, is this related to the dataset? Is it only related to Data_Entry_2017.csv  or something else? Now, I just want to run the program successfully so I just put one picture in images_001, images_002 until images_012 respectively, will this cause problems?

**Comment by n0obcoder** [comment]
have you downloaded the entire 42 gb dataset ? if yes, this problem shouldn't occur. 
pls confirm that you have the complete dataset.

**Comment by zhang0391** [comment]
Yes I have downloaded the entire 42 gb dataset but I create another dataset which only contains 12 pictures instesd of 112120 pictures for experiment. And How long will it take you to run this program？

**Comment by n0obcoder** [comment]
thats what causing the trouble i guess. Try running the code with the original dataset. It will take 8-10 hours probably if you are training  it on a CPU.
Let me know if this solution solved the problem

**Comment by zhang0391** [comment]
Ok I will try it on a GPU, thank you.

**Comment by n0obcoder** [comment]
you can try it on CPU right now if possible, with the complete dataset and let me know if the error has been resolved : )

**Comment by n0obcoder** [comment]
@zhang0391 did it work for you ?

**Comment by zhang0391** [comment]
Hello, I have tried to run the program and solved the previous problems but I don't know what the file pickles is and could you tell me that? Thank you!

**Comment by n0obcoder** [comment]
glad to know that you are finally able to run the code :D 
see there are certain things which require some time to process every time you run the code. So to avoid that, the code generated the pickle files which can be directly used without processing the things everytime you run the code. 
Let me know if you want to know about any specific pickle.
I hope this helps :)

**Comment by zhang0391** [comment]
Yes I would like to know all the three pickles: diease_classes.pickle, test_df.pickle and train_val_df.pickle and how could I open them correctly.
Also, will this program generate a file whose suffix is .pth which storage the parameters when the model is trained?

**Comment by n0obcoder** [comment]
* `diease_classes.pickle` has the names of all the diseases in the ascending order in a list

* `test_df.pickle` is the data dataframe which contains the information  about the test set (https://github.com/n0obcoder/NIH-Chest-X-Rays-Multi-Label-Image-Classification-In-Pytorch/blob/0489269a518c9bc6580dcd80eea0c79ee92a8269/datasets.py#L207)

* `train_val_df.pickle`  is the data dataframe which contains the information  about the train and val set (https://github.com/n0obcoder/NIH-Chest-X-Rays-Multi-Label-Image-Classification-In-Pytorch/blob/0489269a518c9bc6580dcd80eea0c79ee92a8269/datasets.py#L30)

**Comment by zhang0391** [comment]
OK，thank you very much.

**Comment by n0obcoder** [comment]
@zhang0391 I hope that it's clear now : ) can I close this issue now ?

**Comment by zhang0391** [comment]
OK, you can close it. Thanks again!

**Comment by n0obcoder** [comment]
@zhang0391  Cool. You can always open a new issue in case you have any other questions in the future !
CHEERS :)

**Comment by zhang0391** [comment]
OK, I got it!
